# Limits for the Pilz planner
robot_description_planning:
  cartesian_limits:
    max_trans_vel: 0.5
    max_trans_acc:  0.5
    max_trans_dec: -0.5
    max_rot_vel: 1.57

# min distance for no accelartion limits is vel^2/acc
# since robot arm is almost never moving over 
