planning_plugin: pilz_industrial_motion_planner/CommandPlanner
request_adapters: >-
  default_planner_request_adapters/FixWorkspaceBounds
  default_planner_request_adapters/FixStartStateBounds
  default_planner_request_adapters/FixStartStateCollision
  default_planner_request_adapters/FixStartStatePathConstraints
default_planner_config: LIN
capabilities: >-
    pilz_industrial_motion_planner/MoveGroupSequenceAction
    pilz_industrial_motion_planner/MoveGroupSequenceService

planner_configs:
  PTP:
    type: pilz_industrial_motion_planner/PlanningContext
  LIN:
    type: pilz_industrial_motion_planner/PlanningContext

tmr_arm:
  default_planner_config: LIN
  planner_configs:
    - LIN
    - PTP

