# Limits for the Pilz planner
robot_description_planning:
  cartesian_limits:
    max_trans_vel: 0.1 # 0.15 limited to about 0.1 to 0.08 on the real robot
    max_trans_acc:  0.25
    max_trans_dec: -0.25
    max_rot_vel: 1.57

# min distance for no accelartion limits is vel^2/acc
# since robot arm is almost never moving over 
